### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by kyndaqtepammy** [Krupen/FabulousFilter#10]
I'm getting the following error each time I run the app. I followed usage instructions but I'm not sure where 
I'm going wrong:

` java.lang.NullPointerException at com.allattentionhere.fabulousfilter.AAH_FabulousFragment.onStart(AAH_FabulousFragment.java:98)
`

**Comment by Krupen** [comment]
Hi @kyndaqtepammy , 
Apologies for very late reply. I will soon look into it and update the repo.

**Comment by Krupen** [comment]
Hi @kyndaqtepammy , I just updated the library to `v0.0.5`. Please update to this new version and if the issue still persists, please share more code so I can have a look.

**Comment by Krupen** [comment]
I hope the issue is resolved, if not feel free to re-open this issue.

**Comment by iamdeadman** [comment]
Facing the same issue here with v0.0.5, can you help or show what changes did you make inorder to get this working.
