### ISSUE TITLE
Static view is hiding a bit only in my Nokia 6 device 

### ISSUE THREAD

**Issue by shriharsha-bhagwat** [Krupen/FabulousFilter#12]
![screenshot_20180207-173751](https://user-images.githubusercontent.com/21264096/35915726-fa652ce6-0c2d-11e8-86e5-6b008951d2c2.png)
Library works great with all the devices but only in Nokia 6, the bottom part gets hidden slightly. Is there any change we can do to work this in Nokia 6 as well. In the expanded view it looks fine.

**Comment by Krupen** [comment]
Unfortunately I can't test it on Nokia device as there won't be an emulator for it, but for temporary fix you can use static layout with bottom padding.

**Comment by shriharsha-bhagwat** [comment]
Ohh is it. Could there be any other solution other than padding? As adding a bottom padding would not look nice when in Extended mode. Any idea why this is happening in only Nokia 6 devices?

Or else can i add bottom padding only in collapsed mode? If so could you please tell me how i can do it?

**Comment by Krupen** [comment]
No idea as to why it is happening in Nokia devices. Does it happen only in Collapsed mode? Does it trim static view in Expanded mode as well?

**Comment by panyamred** [comment]
I got a similar issue only in the collapsed mode in my OnePlus 6T.

**Comment by TheCodeN00b** [comment]
On devices having the notch and the pill (instead of normal back, multitasking and home buttons) the static view is completely hidden in collapse mode

**Comment by Krupen** [comment]
Does it still repro with version 0.0.6?
