### ISSUE TITLE
Static view disapper in some conditions

### ISSUE THREAD

**Issue by falkontre** [Krupen/FabulousFilter#16]
Static view (reset and apply buttons) disappear on samsung galaxy s8 if using device in full screen (there is no physyical button, but only soft on screen home/back buttons)

I checked source code and seems that in the ViewPagerBottomSheetBehavior:onLayoutChild method there is some issue in recalculate heights during the operation of show/hide.

![20180510_124935](https://user-images.githubusercontent.com/10171792/39870459-bb507610-5461-11e8-9a42-41f99a6ccbcf.jpg)
![20180510_125002](https://user-images.githubusercontent.com/10171792/39870460-bb7d9f6e-5461-11e8-9ecf-73bdadf24cc6.jpg)

**Comment by harshmittal2810** [comment]
I am also getting same error where physical button not available
Or device is in full-screen mode.
If you found any solution please share this.

**Comment by gopalp1709** [comment]
Yes I am alos facing the same issues on devices like MI 8 , Samsung Galaxy 8 etc ,Could please suggest any workaround.

**Comment by AlaaZarifa** [comment]
@Krupen please fix this!

**Comment by Krupen** [comment]
Can you try again with version 0.0.6? There are some fixes for landscape mode which might have fixed this
