### ISSUE TITLE
Getting " Fragment does not have a view" error

### ISSUE THREAD

**Issue by ghost** [Krupen/FabulousFilter#18]
java.lang.IllegalStateException: Fragment does not have a view
 at android.support.v4.app.Fragment$2.onFindViewById(Fragment.java:2308)

I am getting above error every time when i try to open fragment dialog with viewpager 

I have used FragmentStatePagerAdapter.

**Comment by rohmanseo** [comment]
Hi, I'm facing same problem. Have you already solve this problem?

**Comment by Krupen** [comment]
Can you share code which produces this error
