### ISSUE TITLE
Issue in sdk 28

### ISSUE THREAD

**Issue by pravinkorepk94** [Krupen/FabulousFilter#22]
I have error while fab.setVisibility(View.VISIBLE);  ( compileSdkVersion 28)

error:-
VisibilityAwareImageButton.setVisibility can only be called from within the same library group (groupId=com.android.support) less... (Ctrl+F1) 
This API has been flagged with a restriction that has not been met.  Examples of API restrictions: * Method can only be invoked by a subclass * Method can only be accessed from within the same library (defined by the Gradle library group id) .* Method can only be accessed from tests. . You can add your own API restrictions with the @RestrictTo annotation.

Screenshot:
![error1](https://user-images.githubusercontent.com/41328337/49637744-45b82080-fa2c-11e8-8acc-0b6a8e476aed.png)

**Comment by Krupen** [comment]
Is this fixed with the latest update?
