### ISSUE TITLE
cannot be cast to com.allattentionhere.fabulousfilter.AAH_FabulousFragment$Callbacks

### ISSUE THREAD

**Issue by shubh8101996** [Krupen/FabulousFilter#25]
i got error on this line [setCallbacks((Callbacks) getActivity()); //optional; to get back result
        setAnimationListener((AnimationListener) getActivity()); //optional; to get animation callbacks](url)

event i implemented AAH_FabulousFragment.Callbacks, AAH_FabulousFragment.AnimationListener  in my main activity

**Comment by sleepynight2024** [comment]
so why you closed it without explaining?
