### ISSUE TITLE
Lower API version

### ISSUE THREAD

**Issue by Maxxan** [Krupen/FabulousFilter#4]
Isn't it possible to lower API version to 14 or 15 like the latest support libraries? I tried it on Android SDK 15 and it worked fine..

**Comment by Krupen** [comment]
Ok I will check if it works fine. If it is working fine I will change it to lower API version.

**Comment by Krupen** [comment]
Just lowered it to API 15. Update library to version 0.0.4

**Comment by Maxxan** [comment]
Great! :)
