### ISSUE TITLE
Crashes when using ViewPager with FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by darshanpopat** [Krupen/FabulousFilter#6]
Hello, 

I am using this library for Filtering in my application. And it's fantastic in look and use.
I am getting a crash when I use ViewPager with FragmentStatePagerAdapter in this library.
Here is crash : java.lang.IllegalStateException: Fragment does not have a view
And I can't find any solution to stop crashing and make this work.
Can you help me make it run ?

Thanks in Advance.

**Comment by Krupen** [comment]
Hi @darshanpopat , presently this library doesn't work with ViewPager-with-fragments, you will have to use ViewPager-with-views. You can use sample app for reference on how to create ViewPager-with-views. We are presently trying to find a way to make it work with ViewPagers-with-fragments.

**Comment by Krupen** [comment]
Duplicate of https://github.com/Krupen/FabulousFilter/issues/5
